baseURL = "http://www.comp-biophys.com/yamato-lab/"
title = "Yamato Lab"
author = "Yamato Lab members"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Yamato Lab Logo"

  [params.site]
    name = "Yamato Lab"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "Yamato Lab website."
    meta_og_title = "Yamato Lab"
    meta_og_type = "website"
    meta_og_url = "http://comp-biophys.com/yamato-lab/"
    # meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "Yamato Lab"
    # meta_twitter_card = "summary_large_image"
    # meta_twitter_site = "@username"
    # meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "News"
    name = "News"
    url = "/news/"
    weight = 2

  [[menu.main]]
    identifier = "Members"
    name = "Members"
    url = "/members/"
    weight = 3

  [[menu.main]]
    identifier = "Publication"
    name = "Publication"
    url = "/publication/"
    weight = 4

  [[menu.main]]
    identifier = "Resource"
    name = "Resource"
    url = "/resource/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/yamatolab/"
      weight = 2

  [[menu.footer]]
    name = "Access"
    url = "/access"
      weight = 3
[build]
  writeStats = true
