name: Deploy pages

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'

    - name: Setup Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install HUGO's dependencies
      run: npm install -g postcss postcss-cli

    - name: Install Tella's dependencies
      run: npm ci
      working-directory: ./themes/tella

    - name: Build
      run: hugo --minify -d public/yamato-lab

    - name: Copy redirect html file from / to yamatolab/
      run: cp redirect.html public/index.html
    
      # Run when main branch updated
    - name: Deploy pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    
      # Run when develop branch updated
    - name: Deploy Test pages
      if: ${{ github.ref == 'refs/heads/develop' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_KEY_TO_TEST_PAGE_REPO }}
        external_repository: yamatolab/yamatolab.github.io
        publish_dir: ./public
